### ISSUE TITLE
Weiterentwicklung

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [gerrito333/mousehunter-edge#1]
Hallo, ich finde Dein Projekt höchst interessant und würde es gerne Nachbauen.
Leider habe ich so gerade keine Möglichkeit gefunden Dich per PN oder Mail zu kontaktieren, daher mache ich einen Issue dazu auf.

Hast Du in Zukunft evtl. vor das ganze zu erweitern, mit z.B. anderen Messengern, wie z.B. Telegram? Da ich kein IOS nutze wäre der Teil mit der Benachrichtigung für mich nicht möglich.
Ebenso die Speicherung in der AmazonCloud. Vielleicht wäre z.B. eine Speicherung der Daten auf einem NAS-mount möglich?

Würde mich freuen von Dir zu hören.

**Comment by ghost** [comment]
Da gebe ich ein +1

**Comment by gerrito333** [comment]
Danke für Dein Interesse. Wenn Du die Alerts über Telegram oder andere Messenger empfangen möchtest ist das über [Apprise](https://github.com/caronc/apprise) ohne viel Aufwand umsetzbar. Die Bilder direkt auf Dein NAS abzulegen sollte durch einen mount von mausjaeger/images auf das NAS schon erledigt sein. Wenn Du einen Branch aufmachen möchtest können wir das gerne in den Master übernehmen.
